name: Build

on: [ pull_request ]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"

  build:
    name: Build (Go ${{ matrix.go }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - go: 1.11
            os: ubuntu-latest
          - go: 1.12
            os: ubuntu-latest
          - go: 1.13
            os: ubuntu-latest
          - go: 1.14
            os: ubuntu-latest
          - go: 1.11
            os: macos-10.15
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          go install ./cmd/...
          goworld build examples/nil_game
          goworld build examples/test_game
          goworld build examples/test_client
          goworld build examples/chatroom_demo
          goworld build examples/unity_demo
